name: 'Verify Commit'
on:
    push:
        branches: ['*']
    pull_request:
        branches: ['main']
jobs:
    validate:
        runs-on: 'ubuntu-latest'
        steps:
            - uses: 'actions/checkout@v4'

            - name: 'Install dependencies'
              run: 'npm i'

            - name: 'Check code style'
              run: 'npm run style:check'

            - name: 'Lint'
              run: 'npm run lint'
